version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies for tests."
      - npm ci
  build:
    commands:
      - echo "Running Jest tests..."
      - npm test

artifacts:
  files:
    - '**/*'
  discard-paths: no
